#!/usr/bin/env node
/**
 * Runner auto-setup script.
 * Usage: npx ts-node src/setup.ts <RUNNER_API_TOKEN> [CLOUD_API_URL]
 *
 * 1. Calls GET /runner/me with the token to fetch runner/tenant info
 * 2. Auto-detects connected devices to suggest platforms
 * 3. Writes .env file automatically
 * 4. Warns if required tools are missing for detected platforms
 */
import * as fs from 'fs';
import * as path from 'path';
import { execFileSync } from 'child_process';

const token = process.argv[2];
const cloudUrl = process.argv[3] || 'http://localhost:4000/api/v1';

if (!token) {
  console.error('Usage: npm run runner:setup -- <RUNNER_API_TOKEN> [CLOUD_API_URL]');
  console.error('');
  console.error('  RUNNER_API_TOKEN  The ktr_... token from the Cloud Dashboard');
  console.error('  CLOUD_API_URL     (optional) defaults to http://localhost:4000/api/v1');
  process.exit(1);
}

/** Quick device scan to detect platforms (no heavy imports needed) */
function detectPlatforms(): Set<string> {
  const platforms = new Set<string>(['web']);

  // Check for Android devices via adb
  try {
    const output = execFileSync('adb', ['devices'], {
      encoding: 'utf-8',
      timeout: 5000,
      stdio: ['pipe', 'pipe', 'pipe'],
    });
    const lines = output.split('\n').slice(1);
    for (const line of lines) {
      if (line.match(/^\S+\s+(device|unauthorized)/)) {
        platforms.add('android');
        break;
      }
    }
  } catch {}

  // Check for iOS devices via xcrun devicectl or idevice_id
  try {
    const tmpFile = path.join(require('os').tmpdir(), `katab-setup-${process.pid}.json`);
    execFileSync('xcrun', ['devicectl', 'list', 'devices', '--json-output', tmpFile], {
      encoding: 'utf-8',
      timeout: 10000,
      stdio: ['pipe', 'pipe', 'pipe'],
    });
    const data = JSON.parse(fs.readFileSync(tmpFile, 'utf-8'));
    fs.unlinkSync(tmpFile);
    for (const d of data.result?.devices || []) {
      if (d.hardwareProperties?.platform === 'iOS' && d.hardwareProperties?.reality === 'physical') {
        platforms.add('ios');
        break;
      }
    }
  } catch {
    // Fallback: idevice_id
    try {
      const output = execFileSync('idevice_id', ['-l'], {
        encoding: 'utf-8',
        timeout: 5000,
        stdio: ['pipe', 'pipe', 'pipe'],
      }).trim();
      if (output) platforms.add('ios');
    } catch {}
  }

  return platforms;
}

/** Check if a command exists */
function commandExists(cmd: string): boolean {
  try {
    execFileSync('which', [cmd], { encoding: 'utf-8', stdio: ['pipe', 'pipe', 'pipe'] });
    return true;
  } catch { return false; }
}

async function main() {
  console.log('Connecting to Cloud API...');
  console.log(`  URL: ${cloudUrl}`);

  const res = await fetch(`${cloudUrl}/runner/me`, {
    headers: { 'X-Runner-Token': token },
  });

  if (!res.ok) {
    const text = await res.text();
    console.error(`Failed to validate token: ${res.status} ${text}`);
    process.exit(1);
  }

  const info = await res.json() as { runnerName: string; runnerId: string; tenantName: string; tenantId: string };
  console.log(`  Runner: ${info.runnerName} (${info.runnerId})`);
  console.log(`  Tenant: ${info.tenantName} (${info.tenantId})`);

  // Auto-detect connected devices
  console.log('\nDetecting connected devices...');
  const platforms = detectPlatforms();
  const platformsStr = [...platforms].join(',');
  console.log(`  Detected platforms: ${platformsStr}`);

  // Warn about missing dependencies
  if (platforms.has('android')) {
    if (!commandExists('adb')) {
      console.warn('\n  \u26A0 Android platform detected but \'adb\' not found.');
      console.warn('    Install: brew install --cask android-platform-tools');
    }
    if (!commandExists('java')) {
      console.warn('\n  \u26A0 Android platform detected but \'java\' not found.');
      console.warn('    Install: brew install openjdk@17');
    }
    if (!process.env.ANDROID_HOME) {
      console.warn('\n  \u26A0 ANDROID_HOME not set. Appium UiAutomator2 may fail.');
      console.warn('    Install: brew install --cask android-commandlinetools');
    }
  }
  if (platforms.has('ios') && !commandExists('xcrun')) {
    console.warn('\n  \u26A0 iOS platform detected but \'xcrun\' not found.');
    console.warn('    Install: xcode-select --install');
  }

  const envContent = [
    `# Auto-generated by runner:setup`,
    `# Runner: ${info.runnerName}`,
    `# Tenant: ${info.tenantName}`,
    ``,
    `TENANT_ID=${info.tenantId}`,
    `RUNNER_ID=${info.runnerId}`,
    `RUNNER_API_TOKEN=${token}`,
    `CLOUD_API_URL=${cloudUrl}`,
    ``,
    `RUNNER_PLATFORMS=${platformsStr}`,
    `LOCAL_API_PORT=5001`,
    ``,
  ].join('\n');

  const envPath = path.resolve(__dirname, '../.env');
  fs.writeFileSync(envPath, envContent);
  console.log(`\n.env written to ${envPath}`);
  console.log(`  RUNNER_PLATFORMS=${platformsStr}`);
  console.log('\nSetup complete! Start the runner with:');
  console.log('  npm run runner:dev');
}

main().catch((e) => {
  console.error('Setup failed:', e.message);
  process.exit(1);
});
